services:
  postgres:
    restart: always
    env_file: ".env"
    image: postgres
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
      - ./dataset:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
